edu_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from edu_prj import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", views.main_page),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("words/", include("words.urls")),
]


urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

users/urls.py
from django.urls import path
from users import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("memo/", views.memo, name="memo"),
    path("memo/delete/<int:memo_id>/", views.delete_memo, name="delete_memo"),
    path("edit/<int:memo_id>/", views.edit_memo, name="edit_memo"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("edit/<str:field>/", views.profile_edit, name="profile_edit"),
]

words/urls.py
from django.urls import path
from words import views

app_name = "words"
urlpatterns = [
    path("update_words/", views.update_word),
    path("get_sentences/", views.get_sentences),
    path("category/", views.category, name="category"),
    path("learn/",views.learn_words, name="learn_words"),
    path("quiz/", views.quiz, name="quiz"),
    path("quiz_results/", views.quiz_results, name="quiz_results"),
    path("vocabulary/", views.vocabulary, name="vocabulary"),
    path("vocabulary/delete/<int:vocab_id>/", views.delete_vocab, name="delete_vocab"),
    path("filtered_vocab/", views.filtering_vocab, name="filtered_vocab"),
]

words/models.py
from django.db import models
from users.models import User

# Create your models here.
difficulty_choices = (
    ("A1", "입문"),
    ("A2", "초급"),
    ("B1", "중급"),
    ("B2", "중상급"),
    ("C1", "상급"),
    ("C2", "고급")
)

# 주제 테이블
class Topic(models.Model):
    main_topic = models.CharField("메인 주제", max_length=50)
    sub_topic = models.CharField("서브 주제", max_length=50)

    def __str__(self):
        return f"{self.main_topic} > {self.sub_topic}"

# 단어 테이블
class Word(models.Model):
    word = models.CharField("단어", max_length=100)
    definition = models.TextField("정의", blank=True, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, related_name="words", blank=True, null=True)
    difficulty = models.CharField("난이도", max_length=10, choices=difficulty_choices, blank=True, null=True)

    def __str__(self):
        return self.word
    
    
# 문장 테이블
class Sentence(models.Model):
    sentence = models.TextField("예문")
    definition = models.TextField("뜻", null=True, blank=True)
    word = models.ForeignKey(Word, on_delete=models.CASCADE, related_name='sentences', null=True)
    source = models.CharField("출처", max_length=100)

    def __str__(self):
        return self.sentence

# 단어장 테이블
class Vocabulary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    added_at = models.DateTimeField("등록일", auto_now_add=True)

# 퀴즈 테이블
class Quiz(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    sentence = models.ForeignKey(Sentence, on_delete=models.CASCADE)
    user_answer = models.CharField("사용자 입력 정답", max_length=100)
    is_correct = models.BooleanField("정답 여부")
    quiz_date = models.DateTimeField("진행일", auto_now_add=True)

# 메모 테이블
class Memo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField("내용")
    created_at = models.DateTimeField("작성일", auto_now_add=True)
    updated_at = models.DateTimeField("수정일", auto_now=True)

words/views.py
from django.shortcuts import render, redirect, get_object_or_404
from urllib.request import urlopen
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from words.models import Topic, Word, Sentence, Vocabulary, Memo
from random import sample
from collections import defaultdict
from django.http import HttpResponseRedirect

# Create your views here.
def get_words(request):
    # 보류: 바로 객체 생성하기.
    url = "https://www.oxfordlearnersdictionaries.com/topic/"

    driver = webdriver.Chrome()

    driver.get(url) # url 접속

    topics = driver.find_elements(By.CLASS_NAME, "topic-label")
    word_list = []

    for topic_index in range(len(topics)):
        topics = driver.find_elements(By.CLASS_NAME, "topic-label")
        if topic_index >= len(topics):
            break

        try:
            main_topic = topics[topic_index].text.strip()
            topics[topic_index].click()
            time.sleep(2)
        except Exception as e:
            print(f"main topics 에러: {e}")
            continue

        processed_subtopics = []
        topic_boxes = driver.find_elements(By.CLASS_NAME, "topic-box-secondary-heading")

        while len(processed_subtopics) < len(topic_boxes):
            for index, topic_box in enumerate(topic_boxes):
                if index in processed_subtopics:
                    continue
        
                try:
                    topic_boxes = driver.find_elements(By.CLASS_NAME, "topic-box-secondary-heading")
                    sub_topic = topic_boxes[index].text
                    sub_topic = sub_topic.replace("(see all)", "").strip()
                    topic_box = topic_boxes[index]
            
                    topic_box.click()
                    time.sleep(2)
                except Exception as e:
                    print(f"sub-topics 에러: {e}")
                    continue
        
                try:
                    elements = driver.find_elements(By.CSS_SELECTOR, "li[data-hw]")
                    for element in elements:
                        word = element.get_attribute("data-hw")
                        try:
                            difficulty = element.find_element(By.CSS_SELECTOR, "span.belong-to").text
                        except:
                            difficulty = "N/A"

                        try:
                            topic, created = Topic.objects.get_or_create(main_topic=main_topic, sub_topic=sub_topic)
                            Word.objects.get_or_create(word=word, difficulty=difficulty, topic=topic)
                        except Exception as e:
                            print(f"word, difficulty 에러: {e}")
                            continue
                except Exception as e:
                    print(f"processing 에러: {e}")
                    continue
                    
                processed_subtopics.append(index)
        
                driver.back() # 뒤로가기
                time.sleep(2)
        
                topic_boxes = driver.find_elements(By.CLASS_NAME, "topic-box-secondary-heading")

        try:
            back_btn = driver.find_element(By.CSS_SELECTOR, "a.topic_back")
            back_btn.click()
            time.sleep(2)
        except Exception as e:
            print(f"뒤로가기 에러: {e}")
            continue

    driver.quit()

def update_word(request):
    base_url = "https://en.dict.naver.com/#/search?"
    driver = webdriver.Chrome()

    # DB에서 단어를 가져오기 (정의가 없는 단어만)
    words = Word.objects.filter(definition__isnull=True)

    for word_obj in words:
        word = word_obj.word

        # 단어 정의 가져오기
        driver.get(f"{base_url}range=word&query={word}")
        time.sleep(2)

        try:
            origin_div = driver.find_element(By.CSS_SELECTOR, 'div.row')
            mean_elements = origin_div.find_elements(By.CSS_SELECTOR, 'p.mean')
            definition = '\n'.join([mean.text for mean in mean_elements])
            
            # 단어 정의 업데이트
            word_obj.definition = definition
            word_obj.save()
            print(f"단어 뜻 저장 완료: {definition}")
            
        except Exception as e:
            print(f"Error occurred: {e}")
            continue

    driver.quit()

def get_sentences(request):
    base_url = "https://en.dict.naver.com/#/search?"
    driver = webdriver.Chrome()

    # 이미 뜻이 있는 단어들만 해당
    words = Word.objects.filter(definition__isnull=False)

    for word_obj in words:
        word = word_obj.word

        # 예문 페이지로 이동
        driver.get(f"{base_url}range=example&query={word}")
        time.sleep(2)  # 페이지 로드 대기

        try:
            label_check = driver.find_element(By.CSS_SELECTOR, "label.inp_label_check")
            label_check.click()

            time.sleep(2)  # 클릭 후 페이지 로드 대기

            origin_div = driver.find_element(By.CSS_SELECTOR, 'div.origin')
            text_span = origin_div.find_element(By.CSS_SELECTOR, 'span.text')
            
            # span.text 내부의 모든 텍스트를 추출
            sentence = text_span.text
            definition_text = driver.find_element(By.CSS_SELECTOR, 'div.translate').text
            source_text = driver.find_element(By.CSS_SELECTOR, 'a.source').text

            # 문장 객체 생성
            Sentence.objects.get_or_create(
                sentence=sentence,
                definition=definition_text,
                source=source_text,
                word=word_obj,
            )
            print(f"Sentence saved: {sentence}")

        except Exception as e:
            print(f"clicking label 에러: {e}")

    # 브라우저 닫기
    driver.quit()

def category(request):
    # 난이도 선택
    difficulty_choices = (
        ("A1", "입문"),
        ("A2", "초급"),
        ("B1", "중급"),
        ("B2", "중상급"),
        ("C1", "상급"),
        ("C2", "고급")
    )

    # defaultdict 사용하기
    topic_data = defaultdict(list)
    
    # 주제 객체 반환
    for obj in Topic.objects.all():
        # 주제 객체의 main_topic을 키로 하고, 여러 obj(주제 객체)를 값으로 리스트 안에 추가한다.
        topic_data[obj.main_topic].append(obj)
    # topic_data 를 defaultdict 가 아닌 일반 dict 로 묶어준다.
    topic_data = dict(topic_data)

    context = {
        "topic_data": topic_data,
        "difficulty_choices": difficulty_choices,
    }

    return render(request, "words/category.html", context)
    

def learn_words(request):
    topic_id = request.GET.get("topic_id")
    difficulty = request.GET.get("difficulty")

    words_with_sentences = []

    # 조건에 맞는 단어 필터링하기
    # 주제&난이도별 단어인 경우
    if topic_id and difficulty:
        words = Word.objects.filter(topic__id=topic_id, difficulty=difficulty, definition__isnull=False)

    # 주제별 단어인 경우
    elif topic_id:
        words = Word.objects.filter(topic__id=topic_id, definition__isnull=False)

    # 난이도별 단어인 경우
    elif difficulty:
        words = Word.objects.filter(difficulty=difficulty, definition__isnull=False)
    
    else:
        words = Word.objects.filter(definition__isnull=False)
    
    # 그 중 예문이 있는 단어들
    words_with_sentences = [word for word in words if word.sentences.exists()]

    # 랜덤으로 10개 단어 선택
    selected_words = sample(words_with_sentences, min(len(words_with_sentences), 10))

    # template에 아이디 자리인 value 값에 넘겨주기 위해 만든 변수
    selected_words_ids = ",".join([str(word.id) for word in selected_words])

    context = {
        "selected_words": selected_words,
        "selected_words_ids": selected_words_ids,
        "topic_id": topic_id,
        "difficulty": difficulty,
    }

    return render(request, "words/learn_words.html", context)

def filtering_words(user, topic_id, difficulty):
    # 주제&난이도별 단어인 경우
    if topic_id and difficulty:

        # 주제&난이도별 단어 중 10개 단어 선택
        all_words = Word.objects.filter(topic__id=topic_id, difficulty=difficulty, definition__isnull=False, sentences__definition__isnull=False).order_by("?")[:10]

        # 사용자의 단어장에서 단어 객체 반환
        vocab_words = Vocabulary.objects.filter(user=user, word__topic__id=topic_id, word__difficulty=difficulty).values_list("word", flat=True)
    
    # 주제별 단어인 경우
    elif topic_id:
        all_words = Word.objects.filter(topic__id=topic_id, definition__isnull=False, sentences__definition__isnull=False).order_by("?")[:10]
        vocab_words = Vocabulary.objects.filter(user=user, word__topic__id=topic_id).values_list("word", flat=True)

    # 난이도별 단어인 경우
    elif difficulty:
        all_words = Word.objects.filter(difficulty=difficulty, definition__isnull=False, sentences__definition__isnull=False).order_by("?")[:10]
        vocab_words = Vocabulary.objects.filter(user=user, word__difficulty=difficulty).values_list("word", flat=True)

    # 이외 경우
    else:
        all_words = Word.objects.filter(definition__isnull=False, sentences__definition__isnull=False).order_by("?")[:10]
        vocab_words = Vocabulary.objects.filter(user=user).values_list("word", flat=True)

    # 단어장에 있는 단어로 필터링된 단어 가져오기
    vocab_words = Word.objects.filter(id__in=vocab_words, definition__isnull=False, sentences__definition__isnull=False).order_by("?")[:10]

    # 단어가 있는지 확인하고, 중복 없이 두 리스트를 합치기(|)
    combined_words = list(set(all_words) | set(vocab_words))
    if combined_words:
        return combined_words[:10]
    return combined_words

def quiz(request):
    # 쿼리스트링에서 topic_id와 difficulty 값 가져오기
    topic_id = request.GET.get("topic_id")
    difficulty = request.GET.get("difficulty")
    selected_words = request.GET.get("selected_words")

    # POST 방식 요청 시
    if request.method == "POST":
        selected_words = request.POST.get("selected_words")

        if selected_words:
            # 선택된 단어들로 필터링
            word_ids = selected_words.split(",")
            words = Word.objects.filter(id__in=word_ids, definition__isnull=False, sentences__definition__isnull=False)

        else:
            # 주제와 난이도에 따른 필터링
            words = filtering_words(request.user, topic_id, difficulty)

    else:
        # GET 방식 요청 시 선택된 단어가 없는 경우와 동일한 로직
        words = filtering_words(request.user, topic_id, difficulty)

templates/words/category.html
{% extends 'voca_base.html' %}

{% block base_content %}
<div class="ma">
    <h1>Select Topic</h1>
</div>
    <div class="box-container">
        <div class="ma">
            {% for main_topic, sub_topics in topic_data.items %}
                <h2 style="background-color: #1abc9c"> &nbsp {{ main_topic }}</h2>
                {% for sub_topic in sub_topics %}
                    <!-- 학습하기 -->
                    <div style="text-indent : 20px">
                        <h5>{{ sub_topic }}</h5>
                        <form method="GET" action="{% url 'words:learn_words' %}">
                            <label for="difficulty">Level : </label>
                            <select name="difficulty">
                                <option value="">Random</option>
                                {% for key, value in difficulty_choices %}
                                    <option value="{{ key }}">{{ value }}</option>
                                {% endfor %}
                            </select>
                            <input type="hidden" name="topic_id" value="{{ sub_topic.id }}">
                            <button type="submit">New Learning</button>
                        </form>
                        
                        <!-- 문제 풀기 -->
                        <form method="GET" action="{% url 'words:quiz' %}">
                            <label for="difficulty">Level:</label>
                            <select name="difficulty">
                                <option value="">Random</option> 
                                {% for key, value in difficulty_choices %}
                                    <option value="{{ key }}">{{ value }}</option>
                                {% endfor %}
                            </select>
                            <input type="hidden" name="topic_id" value="{{ sub_topic.id }}">
                            <button type="submit">Quiz</button>
                        </form>
                        <br>
                        <br>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
        <div>
            <h1>Select Level</h1>
            <form method="GET" action="{% url 'words:learn_words' %}">
                <label for="difficulty">Level : </label>
                <select name="difficulty">
                    <option value="">Random</option>
                    {% for key, value in difficulty_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                </select>
                <button type="submit">>New Learning</button>
            </form>

            <form method="GET" action="{% url 'words:quiz' %}">
                <label for="difficulty">Select Level</label>
                <select name="difficulty">
                    <option value="">Random</option>
                    {% for key, value in difficulty_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                </select>
                <button type="submit">Quiz</button>
            </form>    
        </div>
    </div>
{% endblock %}

templates/words/filtered_vocab.html
{% extends 'voca_base.html' %}

{% block base_content %}
<div class="box-container">
    <div class="ma">
        <h2>{{ request.user.username }}'s Vocabulary List</h2>
        <a href="{% url 'words:vocabulary' %}">Back to List</a>
        <!-- 현재 선택된 필터를 보여줍니다 -->
        <div style="background-color: gray;">
            <p>Selected topic: 
                {% if topic_id %}
                    {{ topic_id }}
                {% else %}
                    All
                {% endif %}
            </p>
            <p>Selected level: 
                {% if difficulty %}
                    {% for key, value in difficulty_choices %}
                        {% if key == difficulty %}
                            {{ value }}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    All
                {% endif %}
            </p>
        </div>
        
        <!-- 정렬 옵션 -->
        <form method="GET" action="{% url 'words:filtered_vocab' %}">
            <input type="hidden" name="topic_id" value="{{ topic_id }}">
            <input type="hidden" name="difficulty" value="{{ difficulty }}">

            <label for="order_by">sort by:</label>
            <select name="order_by">
                <option value="word__word" {% if order_by == "word__word" %}selected{% endif %}>Spelling</option>
            </select>

            <label for="direction">order by:</label>
            <select name="direction">
                <option value="asc" {% if direction == "asc" %}selected{% endif %}>ascending</option>
                <option value="desc" {% if direction == "desc" %}selected{% endif %}>descending</option>
            </select>

            <button type="submit" class="btn btn-primary">Arrange</button>
            <br>
            <br>
        </form>

        <!-- 필터링된 단어 목록 -->
        <div>
            {% for vocab in vocabulary %}
                <p class="voca">Word : {{ vocab.word.word }}</p>
                <p class="voca01">Meaning&nbsp&nbsp&nbsp&nbsp: {{ vocab.word.definition }}</p>

                <!-- 삭제 버튼 (모달 트리거) -->
                <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete_modal_{{ vocab.id }}">Delete</button>
                <br>
                <br>

                <!-- 삭제 모달 -->
                <div id="delete_modal_{{ vocab.id }}" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Warning</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Are you sure you want to delete this Word? Click continue to delete the word. If not, click cancel.</p>
                            </div>
                            <div class="modal-footer">
                                <form id="deleteForm_{{ vocab.id }}" method="POST" action="{% url 'words:delete_vocab' vocab.id %}?{% if topic_id %}topic_id={{ topic_id }}{% endif %}{% if difficulty %}&difficulty={{ difficulty }}{% endif %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Continue</button>
                                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include 'add_memo.html' %}
</div>

{% endblock %}

templates/words/learn_words.html
{% extends 'voca_base.html' %}

{% block base_content %}
<div class="box-container">
    <div class="ma">
        <h1 style="background-color: #1abc9c;" >Learn Words</h1>
        <h1>
            <a href ="{% url 'words:category' %}">Category</a>
        </h1>

        {% for word in selected_words %}
            <h2 style="font-size: 35px;">{{ word.word }}</h2>
            <p style="color: #1abc9c; font-size: 20px;">Meaning : </p>
            <p style="font-size: 20px;">{{ word.definition }}</p>
            <p style="color: #1abc9c; font-size: 20px;">Example Sentences : </p>
            <p style="font-size: 20px;">
            {% for sentence in word.sentences.all %}
                {{ sentence.sentence }} - {{ sentence.definition }}
            {% endfor %}
            </p>
            <br>
            <br>
        {% endfor %}
    </div>
    <div>
        <br>
        <br>
        <br>
        <br>
        <!-- 문제 풀기 폼 -->
        <form method="POST" action="{% url 'words:quiz' %}">
            {% csrf_token %}
            {% for word in selected_words %}
                <input type="hidden" name="selected_words" value="{{ selected_words_ids }}">
                <input type="hidden" name="topic_id" value="{{ topic_id }}">
                <input type="hidden" name="difficulty" value="{{ difficulty }}">
            {% endfor %}
            <p style="font-size: 35px">Go to Quiz</p>
            <button type="submit">Quiz</button>
        </form>
    </div>
</div>
{% endblock %}

templates/words/quiz.html
{% extends 'voca_base.html' %}

{% block base_content %}
<div class="ma" style="background-color: #1abc9c;">
    <h2>Quiz</h2>
</div>
<div class="box-container">
    <div class="ma">
        <form method="POST" action="{% url 'words:quiz_results' %}">
            {% csrf_token %}
            {% for word in words %}
                <label style="font-size: 20px;">{{ word.definition|linebreaksbr }}</label>
                <br>
                <input type="text" name="answers_{{ word.id }}" placeholder="type your answer">
                <br>
                <br>
                <br>
            {% endfor %}
    </div>
    <div>
        <p style="font-size: 35px">Submit</p>
        <button type="submit">Submit</button>
    </div>
    </form> 
</div>
{% endblock %}

templates/words/quiz_results.html
{% extends 'voca_base.html' %}

{% block base_content %}
<div class="ma" style="background-color: #1abc9c;">
    <h2>Result</h2>
</div>
<div class="box-container">
    <div class="ma">
        {% for result in results %}
            <div>
                <h5 style="font-size: 25px">{{ result.word.word }}</h5>
                <p style="font-size: 20px">({{ result.word.definition|linebreaksbr }})</p>
            </div>
            <div style="display:inline; font-size: 15px;">
                Corrected : 
                {% if result.correct %}
                    <p style="display:inline; color: rgba(97, 248, 147, 0.997);">correct</p>
                    <br>
                {% else %}
                    <p style="display:inline; color: rgb(255, 0, 0);">Incorrect</p>
                    <br>
                {% endif %}
                My Answer : {{ result.user_answer }}
                <br>
                <br>
                <br>
                <br>
                <br>
            </div>
        {% endfor %}
    </div>
    <div>
        <p style="font-size: 35px">Corrected: {{ correct_count }}/{{ total_count }}</p>
    <!-- 단어장으로 이동하기 -->
        <form method="GET" action="{% url 'words:vocabulary' %}">
            <button type="submit">Go to My Vocabulary List</button>
        </form>
    </div>
</div>
{% endblock %}

templates/words/vocabulary.html
{% extends 'voca_base.html' %}

{% block base_content %}
<div class="box-container">
    <div class="ma">
        <h2>{{ request.user.username }}'s Vocabulary List</h2>
<!-- 필터 옵션 -->
        <div class="box-container" style="background-color: gray;">
            <div>
            <form method="GET" action="{% url 'words:filtered_vocab' %}">
                <label for="topic_id" style="font-size: 20px">Topic:</label>
                <select name="topic_id">
                    <option value="">Random</option>
                    {% for topic in topics %}
                        <option value="{{ topic.main_topic }}">{{ topic.main_topic }}</option>
                    {% endfor %}
                </select>
                <br>
                <label for="difficulty" style="font-size: 20px;">Level:</label>
                <select name="difficulty">
                    <option value="">Random</option>
                    {% for key, value in difficulty_choices %}
                        <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <p>&nbsp&nbsp&nbsp&nbsp&nbsp</p>
                <button type="submit">Apply Filter</button>
            </div>
            </form>
        </div>
        <br>
            <!-- 단어 목록 -->
            {% for vocab in vocabulary %}
                <p class="voca">Word : {{ vocab.word.word }}</p>
                <p class="voca01">Meaning : {{ vocab.word.definition }}</p>
                
                <!-- 단어 삭제 기능 -->
                <form method="POST" action="{% url 'words:delete_vocab' vocab.id %}">
                    {% csrf_token %}
                </form>
                
                    <!-- 삭제 버튼 (모달 트리거) -->
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete_modal_{{ vocab.id }}">Delete</button>
                    <br>
                    <br>

                    <!-- 삭제 모달 -->
                    <div id="delete_modal_{{ vocab.id }}" class="modal fade" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Warning</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete this Word? Click continue to delete the word. If not, click cancel.</p>
                                </div>
                                <div class="modal-footer">
                                    <form id="deleteForm_{{ vocab.id }}" method="POST" action="{% url 'words:delete_vocab' vocab.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Continue</button>
                                        <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endfor %}
    </div>
            {% include 'add_memo.html' %}
</div>
{% endblock %}