edu_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from edu_prj import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", views.main_page),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("words/", include("words.urls")),
]


urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

users/urls.py
from django.urls import path
from users import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("memo/", views.memo, name="memo"),
    path("memo/delete/<int:memo_id>/", views.delete_memo, name="delete_memo"),
    path("edit/<int:memo_id>/", views.edit_memo, name="edit_memo"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("edit/<str:field>/", views.profile_edit, name="profile_edit"),
]

words/urls.py
from django.urls import path
from words import views

app_name = "words"
urlpatterns = [
    path("update_words/", views.update_word),
    path("get_sentences/", views.get_sentences),
    path("category/", views.category, name="category"),
    path("learn/",views.learn_words, name="learn_words"),
    path("quiz/", views.quiz, name="quiz"),
    path("quiz_results/", views.quiz_results, name="quiz_results"),
    path("vocabulary/", views.vocabulary, name="vocabulary"),
    path("vocabulary/delete/<int:vocab_id>/", views.delete_vocab, name="delete_vocab"),
    path("filtered_vocab/", views.filtering_vocab, name="filtered_vocab"),
]

templates/add_memo.html
<div class="ma_01">
    <div id="aside">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <br>
                <br>
                <label>MEMO</label>
                <br>
                <textarea name="content" cols="70" rows="20"></textarea>
                <br>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>


<!-- Bootstrap JavaScript and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <script src="{% static 'js/scripts.js' %}"></script>
        <title>Englisth Learner</title>
        <!-- Favicon-->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
        <style>       
        * {
        font-family: "Jua", sans-serif;
        font-weight: 400;
        font-style: normal;
        }
        </style>

        {% block style %}
        {% endblock %}
        {% block head %}
        {% endblock %}
    

    </head>
    <body>
        {% block base_content %}
        {% endblock %}
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

    <section class="page-section portfolio" id="portfolio">
        <div class="container">
            <!-- Portfolio Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
        </div>
    </section>

    <section class="page-section bg-primary text-white mb-0" id="about">
        <div class="container">
            <!-- About Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- About Section Content-->
            <div class="row">
                <div class="col-lg-4 ms-auto"><p class="lead">Page you are at is where you can learn English. You can learn simple examples or expressions of how the words are used along with the English words. After learning the words, take quiz time, and check the results of the questions and whether they are correct or not.</p></div>
                <div class="col-lg-4 me-auto"><p class="lead">Once you solve quizzes, words list will automatically be uploaded to your vocabulary list. Make your own vocabulary and move forward to improve your English. We will do our best for you to enjoy learning words by investing short time every day.</p></div>
            </div>
            <!-- About Section Button-->
            <div class="text-center mt-4">
            </div>
        </div>
    </section>


    <!-- Footer-->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">
                <!-- Footer Location-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">
                        136, Seogang-ro, Mapo-gu, 
                        <br />
                        Seoul, Republic of Korea
                    </p>
                </div>
                <!-- Footer Social Icons-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Contact</h4>
                    <p>kim gingh : 010-4232-1984</p>
                    <p>Jade Moon : 010-8603-2561</p>
                    <p>Hwacs : 010-**89-59**</p>
                </div>
                <!-- Footer About Text-->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About Team Communism</h4>
                    <p class="lead mb-0">
                        The team was named without thinking.
                        <br />
                        Team Communism has three members.
                    </p>
                </div>
            </div>
        </div>
    </footer>
</html>

templates/base_01.html
{% extends 'base.html' %}

{% block style %}
    {% include 'nav.html' %}
    <header style="height:120px">
    </header>
{% endblock %}

{% block head %}
{% endblock %}

{% block base_content %}
{% endblock %}

templates/login_base.html
<header style="height: 200px; background-color: #1abc9c;">
    <div class="container d-flex align-items-center flex-column" style="margin-top: 50px; margin-bottom: 30px;">
        <!-- Masthead Avatar Image-->
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">English Learner</h1>
        <br>
        <div class="divider-custom divider-light" style="color: black;">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <br>
        <br>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
        </div>
      </div>
</header>

templates/main.html
{% extends 'base.html' %}

{% block head %}
{% include 'nav.html' %}
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">English Learner</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p>
        </div>
    </header>
{% endblock %}

{% block base_content %}

<section class="dark">
    <button class="button" onclick = "location.href = '/words/category/' " style = "background-color: var(--gray-0);">Category</button> 
</section>

<section class="light">
    <button class="button" onclick = "location.href = '/words/vocabulary/' " style = "background-color: var(--gray-9);">Vocabulary List</button> 
</section>
    
    
{% endblock %}

templates/nav.html
        <!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href='/'>mainpage</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'users:profile' user.id %}">Profile</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'users:memo' %}">Memo</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'words:vocabulary' %}">Vocabulary List</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'users:logout' %}">Sign out</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/voca_base.html
{% extends 'base_01.html' %}

{% block head %}
<!-- Bootstrap CSS -->

<style>
    .voca{
    background : #1abc9c;
    font-size: 30px;
    }

    .voca01{
    background : #ccebe8;
    font-size: 20px;
    }

    .box-container {
    display: flex;
    }
    
    .ma {
        width: 500px;
        margin-left: 50px;
        margin-right: 500px;
    }

    .ma_01 {
        margin-right: 100px;
    }



</style>
{% endblock %}

{% block base_content %}
{% endblock %}