edu_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from edu_prj import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", views.main_page),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("words/", include("words.urls")),
]


urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

users/urls.py
from django.urls import path
from users import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("memo/", views.memo, name="memo"),
    path("memo/delete/<int:memo_id>/", views.delete_memo, name="delete_memo"),
    path("edit/<int:memo_id>/", views.edit_memo, name="edit_memo"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("edit/<str:field>/", views.profile_edit, name="profile_edit"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    name = models.CharField(max_length=10)
    email = models.EmailField("이메일", blank=True, null=True)
    profile_image = models.ImageField("프로필 이미지", upload_to='user/profile', blank=True, null=True)
    joined_at = models.DateTimeField("가입일", auto_now_add=True)

    def __str__(self):
        return self.username
    
    

users/forms.py
from django import forms
from users.models import User
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (3자리 이상)"},
        ),
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"},
        ),
    )

class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(required=False)
    name = forms.CharField()
    profile_image = forms.ImageField(required=False)

    def clean_username(self):
        username = self.cleaned_data["username"]

        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용 중입니다")
        
        return username
    
    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            # password2 필드에 오류를 추가
            self.add_error("password2", "비밀번호와 비밀번호 확인란의 값이 다릅니다")

    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]
        name = self.cleaned_data["name"]
        email = self.cleaned_data.get("email")
        profile_image = self.cleaned_data.get("profile_image")

        user = User.objects.create_user(
            username = username,
            password = password1,
            name = name,
            email = email,
            profile_image = profile_image,
        )
        return user

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import LoginForm, SignupForm
from users.models import User
from words.models import Memo
import re
from django.contrib import messages
from django.http import HttpResponse


# Create your views here.
def login_view(request):
    # 이미 로그인되어 있는 경우
    if request.user.is_authenticated:
        return redirect("/")
    
    if request.method == "POST":
        # LoginForm 인스턴스를 만들며, 입력 데이터는 request.POST 를 사용
        form = LoginForm(data=request.POST)

        # # LoginForm 에 들어온 데이터가 적절한지 유효성 검사
        # print("form.is_valid(): ", form.is_valid())

        # # 유효성 검사 이후에는 cleaned_data 에서 데이터를 가져와 사용
        # print("form.cleaned_data: ", form.cleaned_data)
        # return render(request, "user/login.html", {"form": form})

        # LoginForm 에 전달된 데이터가 유효하다면
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password 에 해당하는 사용자가 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 피드 페이지로 리다이렉트
                login(request, user)
                return redirect("/")
            
            # 해당 사용자가 없다면 form에 에러 추가
            else:
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다")

        # 어떤 이유든, 실패한 경우라면 다시 LoginForm 을 사용한 로그인 페이지 렌더링
        return render(request, "users/login.html", {"form": form})
    
    else:
        # LoginForm 인스턴스를 생성
        form = LoginForm()

        # 생성한 LoginForm 인스턴스를 템플릿에 "form" 이라는 키로 전달
        return render(request, "users/login.html", {"form": form})
    
def logout_view(request):
    # logout 함수 호출에 request를 전달
    logout(request)

    # logout 처리 후, 로그인페이지로 이동
    return redirect("/users/login/")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)

        # Form에 에러가 없다면 form의 save() 메서드로 사용자를 생성
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/")

    # GET 요청에서는 빈 Form을 보여줌
    else:
        # SignupForm 인스턴스를 생성, Template에 전달
        form = SignupForm()

    context = {"form": form}
    return render(request, "users/signup.html", context)

def memo(request):
    # 최근 작성된 글이 위로 오도록 내림차순 정렬
    memos = Memo.objects.filter(user=request.user).order_by('-created_at')

    # 수정할 메모를 가져옴
    edit_memo_id = request.GET.get('edit_memo_id')
    edit_memo = None

    # 수정할 메모 아이디를 가져온 경우 덮어쓰기
    if edit_memo_id:
        edit_memo = get_object_or_404(Memo, id=edit_memo_id, user=request.user)

    # POST 요청 시
    if request.method == "POST":
        content = request.POST["content"]
        memo_id = request.POST.get("memo_id")

        if memo_id:
            # 기존 메모 수정
            memo = get_object_or_404(Memo, id=memo_id, user=request.user)
            memo.content = content
            memo.save()
        else:
            # 새 메모 생성
            memo = Memo.objects.create(content=content, user=request.user)
            memo.save()
        
        return redirect("/users/memo/")
    
    context = {
        "memos": memos,
        "edit_memo": edit_memo,
    }

    return render(request, "users/memo.html", context)

def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id, user=request.user)

    if request.method == "POST":
        memo.delete()
        return redirect("/users/memo/")
    
    return HttpResponse(status=405)

def edit_memo(request, memo_id):
    # 수정할 Todo 객체를 가져오고, 없다면 404 에러 반환
    memo = get_object_or_404(Memo, id=memo_id)

    if request.method == "POST":
        # list나 category 값이 없으면 원래 값을 그대로 사용
        memo.content = request.POST.get("content", memo.content)
        memo.save()
        return redirect("/users/memo/")
    
    # GET 요청 시 기존 데이터와 함께 수정 페이지 렌더링
    return render(request, "users/edit_memo.html", {"memo": memo})

def profile(request, user_id):
    profile_user = get_object_or_404(User, id=user_id)

    # 요청을 보낸 사용자가 프로필 사용자가 아닐 때
    if request.user.is_authenticated and profile_user != request.user:
        # 팔로우 여부 확인
        pass

    context = {
        "profile_user": profile_user,
    }

    return render(request, "users/profile.html", context)

def profile_edit(request, field):
    # 사용자가 로그인된 상태가 아니라면 로그인 페이지로 리다이렉트
    if not request.user.is_authenticated:
        return redirect('/user/login/')
    
    profile_user = request.user

    # POST 요청 시
    if request.method == "POST":
        # field가 profile_image일 때
        if field == "profile_image":
            profile_user.profile_image = request.FILES.get("profile_image")

        # field가 nickname일 때
        elif field == "name":
            profile_user.name = request.POST.get("name", profile_user.name)

        # field가 email일 때
        elif field == "email":
            profile_user.email = request.POST.get("email", profile_user.email)
            email_regex = re.compile(r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')

            if not email_regex.search(profile_user.email):
                messages.warning(request, "Incorrect email address.")
                return redirect("users:profile", user_id=profile_user.id)
            

        # field에 이외 잘못된 값이 들어갔을 때, 프로필 페이지로 리다이렉트
        else:
            return redirect("users:profile", user_id=profile_user.id)
        
        profile_user.save()
        # 수정된 내용을 반영한 후 리다이렉트
        return redirect("users:profile", user_id=profile_user.id)
    
    # GET 요청 시 기존 데이터와 함께 수정 폼 호출
    return render(request, "users:profile_edit", {"profile_user": profile_user})

templates/users/login.html
{% extends 'base.html' %}

{% block head %}
    {% include 'login_base.html' %}
{% endblock %}

{% block base_content %}
    <div id="login" style="margin: 0 auto; margin-top: 30px;">
        <form method="POST">
            <h2 style="color: #1abc9c; text-align: center;">Login</h2>
            <br>
            {% csrf_token %}
            {{ form.as_p }}
            <div style="text-align: center;">
            <button type="submit" class="btn btn-login">Sign in</button>
            <a href="{% url 'users:signup' %}">Register</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/users/memo.html
{% extends 'base_01.html' %}

{% block head %}
<!-- Bootstrap CSS -->

<style>
    .item:nth-child(even) {
    background : lightblue;
    }
    .item:nth-child(odd) {
    background : #1abc9c;
    }

    .box-container {
    display: flex;
    }
    
    .ma {
        margin-left: 100px;
        margin-right: 500px;
    }

    .ma_01 {
        margin-right: 100px;
    }

</style>
{% endblock %}

{% block base_content %}
<div class="box-container">
    <div class="ma">
        <h1>MEMO</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea name="content" cols="100" rows="15">{% if edit_memo %}{{ edit_memo.content }}{% endif %}</textarea>
            <br>
            <input type="hidden" id="memoId" name="memo_id" value="{% if edit_memo %}{{ edit_memo.id }}{% endif %}">
            <button type="submit" class="btn btn-primary">{% if edit_memo %}Edit{% else %}Take Notes{% endif %}</button>
        </form>

    </div>
    <br>
    <div class="ma_01">
        <!-- 메모장 기능 구현 -->
        <div>
        {% for memo in memos %}
            <div style="width: 500px; background-color :#b0f9eb;" >
            <p class="item">Content: {{ memo.content|truncatechars:20 }}{% if memo.content|length > 10 %}...{% endif %}</p>
            <p>Created at: {{ memo.created_at }}</p>
            <p>Updated at:{{ memo.updated_at }}</p>
            <form method="POST" action="{% url 'users:delete_memo' memo.id %}">
                {% csrf_token %}
            </form>

            <!-- 수정 버튼 -->
            <form method="GET" action="{% url 'users:memo' %}">
                <input type="hidden" name="edit_memo_id" value="{{ memo.id }}">
                <button type="submit" class="btn btn-primary btn-sm">See More</button>
            </form>

            <!-- 삭제 버튼 (모달 트리거) -->
            <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete_modal" data-memo-id="{{ memo.id }}">Delete</button>
            </div>
            <div style="background-color:transparent;"> &nbsp </div>
        {% endfor %}
        </div>
    </div>
</div>     
    
<!-- 삭제 모달 -->
<div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Warning</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this MEMO? Click continue to delete the memo. If not, click cancel.</p>
            </div>
            <div class="modal-footer">
                <form id="deleteForm" method="POST" action="">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Continue</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

    <!-- Bootstrap JavaScript and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        $('#delete_modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var memoId = button.data('memo-id');
            var action = `{% url 'users:delete_memo' 0 %}`.replace('0', memoId);
            $('#deleteForm').attr('action', action);
        });
    </script>
{% endblock %}

templates/users/profile.html
{% extends 'base_01.html' %}

{% block head %}
<style>

    .box-container {
    display: flex;
    }
    
    .ma {
        margin-left: 100px;
        margin-right: 500px;
    }

    .ma_01 {
        margin-right: 100px;
    }

</style>
{% endblock %}

{% block base_content %}
<div class="box-container">
    <div class="ma">
        <h1>profile</h1>
        <div>
            {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}" width="600" height="400">
            {% else %}
                <img src="https://wallpapercave.com/wp/wp13396427.jpg" width="600" height="400">
            {% endif %}
        </div>
        
        <div>
        {% if profile_user == request.user %}
            <button onclick="document.getElementById('edit_image_form').style.display='block'">Change Profile Image</button>

        <!-- 프로필 이미지 수정 폼 -->
            <form method="POST" id="edit_image_form" action="{% url 'users:profile_edit' 'profile_image' %}" enctype="multipart/form-data" style="display:none;">
                {% csrf_token %}
                <input type="file" name="profile_image">
                <button type="submit">Save</button>
            </form>
        {% endif %}
        </div>
    </div>
    <div>
        <div>
            <br>
            <br>
            <h2>Name : {{ profile_user.name }} </h2>
            {% if profile_user == request.user %}
                <button onclick="document.getElementById('edit_nickname_form').style.display='block'">Change Name</button>

                <!-- 닉네임 수정 폼 -->
                <form method="POST" id="edit_nickname_form" action="{% url 'users:profile_edit' 'name' %}" style="display:none;">
                    {% csrf_token %}
                    <input type="text" name="name" value="{{ profile_user.name }}">
                    <button type="submit">Save</button>
                </form>
            {% endif %}
        </div>
        
        <br>
        <div>
        <h3> Email-address : {{ profile_user.email }}</h3>
            {% if profile_user == request.user %}
                <button  id="email_btn" onclick="document.getElementById('edit_email_form').style.display='block'">Change Email</button>

                <form method="POST" id="edit_email_form" action="{% url 'users:profile_edit' 'email' %}" style="display:none;">
                    {% csrf_token %}
                    <input type="text" name="email" value="{{ profile_user.email }}">
                    <button type="submit">Save</button>
                </form>
            {% endif %}
        <!-- message는 이메일 형식에 맞지 않습니다. -->
        {% for message in messages %}
            {{ message.tag }}
            {{ message }}
        {% endfor %}
        
        </div>
    </div>
</div>
    
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block head %}
    {% include 'login_base.html' %}
{% endblock %}

{% block base_content %}
    <div id="signup" style=" margin: 0 auto; margin-top: 30px;">
        <form method="POST" enctype="multipart/form-data">
            <h1 style="text-align: center; color: #1abc9c;">Register</h1>
            <br>
            {% csrf_token %}
            {{ form.as_p }}
            <div style="text-align: center;">
                <button type="submit" class="btn btn-signup">Register</button>
                <a href="{% url 'users:login' %}">Sign in</a>
            </div>
        </form>
    </div>
{% endblock %}


id="contactForm